# see https://github.com/hvr/multi-ghc-travis
env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.2

install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.20 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - cabal-1.20 update

script:
 - cabal-1.20 sdist
   # use -j1 to see full build logs. remove when cabal is fixed.
 - cabal-1.20 install -v -j1 --run-tests "dist/$(cabal-1.20 info . | awk '{print $2 ".tar.gz";exit}')"
